environment:
  version: 1.0.0
  versionSuffix:

init:
- ps: $env:buildVersion = "$env:version$env:versionSuffix.$env:appveyor_build_number"
- ps: $env:nugetVersion = "$env:version$env:versionSuffix"
- ps: Update-AppveyorBuild -Version $env:buildVersion

image: Visual Studio 2017

install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build:
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
  #- ps: Vsix-TokenReplacement SelEx\source.extension.cs 'Version = "([0-9\\.]+)"' 'Version = "{version}"'

build_script:
  - nuget restore -Verbosity quiet
  - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

after_test:
  - ps: Vsix-PushArtifacts | Vsix-PublishToGallery

configuration: Debug
